SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
INSERT INTO `users` VALUES (1,'demo_user_1','$2y$10$YGrnNg9aWveISimj.70mJOhjdUI14ZSSoWAccUBa9Pz8YJcvotbJS','demo@local.dev',NULL,'2019-03-09 01:04:26',NULL,NULL,'OwDHQONya2Dpmh6WkjGFAP3lXhNOvsS9BKH5oHSwix4K58YFSqClW2YrpAfXqa5FnurcOapsweDLVas9VSH9Gk87t9hXdxF2UmpjDymeqwhooPayVgtQCZqAkzymTc9GNxbWkh7XkdsmPMX15BCz9txlndFXTOQeRRYOOu0bHjYPFU4TcrLxPdaoOfsdvNXlYCNlOZPjBPF15c69BEHwFEUbr2WXRh0gQRfNJTiLEJ2HhqsjUSlO2eYlEw','2019-03-09 01:04:15');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
